### ISSUE TITLE
Extending the class

### ISSUE THREAD

**Issue by upchuk** [sgrodzicki/pingdom#2]
Hey there,

Thanks for this class. There is one problem though: you have 4 call methods to the API when there are many other calls you could make to Pingdom. But at the same time, the credential variables are marked as private so one cannot extend the class to provide additional functionality.

Maybe you'll consider marking the variables protected so that extending classes can access them or provide protected getters.

Thanks!

**Comment by sgrodzicki** [comment]
@upchuk feel free to make a pull request reflecting your proposal.

**Comment by upchuk** [comment]
@sgrodzicki That was quick. Sure, will do, thanks! :)
